blog/urls.py
from django.urls import path 
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category_list, name='category_list'),
    path('release/', views.post_release, name='post_release'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post_edit/<int:post_id>/', views.post_edit, name='post_edit'),
    path('delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('search/', views.search, name='search'),
    path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
    path('comment/<int:post_id>/', views.post_comment, name='post_comment'),
    path('comment_delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('my_post/', views.my_post_list, name='my_post'),
    path('favorite_add/<int:post_id>/', views.favorite_add, name='favorite_add'),
    path('favorite_del/<int:post_id>/', views.favorite_del, name='favorite_del'),
    path('my_favorite/', views.my_favorite, name='my_favorite'),
    path('post_list/<int:user_id>/', views.post_list, name='post_list'),
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'  # 定义一个命名空间  用于区分不同应用的连接地址

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.register, name='register'),
    path('active/<active_code>', views.active_user, name='active_user'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('forget_pwd_url/<active_code>', views.forget_pwd_url, name='forget_pwd_url'),
    # path('my_profile/', views.my_profile, name='my_profile'),
    path('user_profile/<username>/', views.user_profile, name='user_profile'),
    path('logout/', views.logout_view, name='logout'),
    path('editor_users/', views.editor_users, name='editor_users'),
    path('modify_pwd/', views.modify_pwd, name='modify_pwd'),
    path('check_pwd/', views.check_pwd, name='check_pwd'),
]

blog/models.py
from django.contrib.auth.models import User
from django.utils.functional import cached_property  # 缓存装饰器
from django.template.loader import render_to_string  # 渲染模板
from django.db import models
from ckeditor.fields import RichTextField
from mptt.models import MPTTModel
from users.models import User


# Create your models here.
class Category(models.Model):
    """ 博客的分类模型 """
    name = models.CharField(max_length=32, verbose_name="分类名称")
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name="分类描述")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "博客分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """ 文章标签 """
    name = models.CharField(max_length=10, verbose_name="文章标签")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    """ 文章 """
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="作者")
    title = models.CharField(max_length=61, verbose_name="文章标题")
    desc = models.CharField(max_length=500, blank=True, default='', verbose_name="文章描述")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    content = models.TextField(max_length=20000, blank=True, default='', verbose_name="内容")
    # content = RichTextField(max_length=20000, blank=True, default='', verbose_name="内容")
    tags = models.ForeignKey(Tag, blank=True, null=True, on_delete=models.CASCADE, verbose_name="文章标签")
    is_hot = models.BooleanField(default=False, verbose_name="是否热门")  # 手动热门推荐
    pv = models.IntegerField(default=0, verbose_name="浏览量")  # 浏览量
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Sidebar(models.Model):
    # 侧边栏的模型数据

    STATUS = (
        (1, '隐藏'),
        (2, '展示')
    )

    DISPLAY_TYPE = (
        (1, '搜索'),
        (2, '最新文章'),
        (3, '最热文章'),
        (4, '最近评论'),
        (5, '文章归档'),
        (6, 'HTML')
    )

    title = models.CharField(max_length=50, verbose_name="模块名称")  # 模块名称
    display_type = models.PositiveIntegerField(default=1, choices=DISPLAY_TYPE,
                                               verbose_name="展示类型")  # 侧边栏  搜索框/最新文章/热门文章/HTML自定义等
    content = models.CharField(max_length=500, blank=True, default='', verbose_name="内容",
                               help_text="如果设置的不是HTML类型，可为空")  # 这个字段是专门用来给HTML类型用的，其他类型可为空
    sort = models.PositiveIntegerField(default=1, verbose_name="排序", help_text='序号越大越靠前')
    status = models.PositiveIntegerField(default=2, choices=STATUS, verbose_name="状态")  # 隐藏  显示状态
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")  # 时间

    class Meta:
        verbose_name = "侧边栏"
        verbose_name_plural = verbose_name
        ordering = ['-sort']

    def __str__(self):
        return self.title

    @classmethod  # 类方法装饰器，这个就变成了这个类的一个方法可以调用
    def get_sidebar(cls):
        return cls.objects.filter(status=2)  # 查询到所有允许展示的模块

    @property  # 成为一个类属性，调用的时候不需要后边的(),是只读的，用户没办法修改
    def get_content(self):
        if self.display_type == 1:
            context = {

            }
            return render_to_string('blog/sidebar/search.html', context=context)
        elif self.display_type == 2:
            context = {

            }
            return render_to_string('blog/sidebar/new_post.html', context=context)
        elif self.display_type == 3:
            context = {

            }
            return render_to_string('blog/sidebar/hot_post.html', context=context)
        elif self.display_type == 4:
            context = {

            }
            return render_to_string('blog/sidebar/comment.html', context=context)
        elif self.display_type == 5:  # 文章归档
            context = {

            }
            return render_to_string('blog/sidebar/archives.html', context=context)
        elif self.display_type == 6:  # 自定义侧边栏

            return self.content  # 在侧边栏直接使用这里的html，模板中必须使用safe过滤器去渲染HTML


class Comment(models.Model):  # 博文评论
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = '评论'

    def __str__(self):
        return self.body[:20]


class Favorite(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='favorite')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='favorite')

    class Meta:
        verbose_name = "收藏"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.post.title

blog/forms.py
from .models import Comment, Post
from django import forms
from ckeditor.fields import RichTextField


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'desc', 'content', 'category']

    class Media:
        css = {
            'all': ('ckeditor5/cked.css',)
        }

        js = (
            'https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js',
            'ckeditor5/ckeditor.js',
            'ckeditor5/translations/zh.js',
            # 'ckeditor5/config.js'
        )


class CommentForm(forms.ModelForm):  # 文章评论表单

    class Meta:
        model = Comment
        fields = ['body']

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q, F
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import CommentForm, PostForm
from .models import Post, Comment, Favorite, Category, Post
from users.models import User


def index(request):
    # 首页
    post_list = Post.objects.all()  # 查询到所有的文章,queryset
    # 分页方法
    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'blog/index.html', context)


def category_list(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    # 获取当前分类下的所有文章
    posts = category.post_set.all()
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'category': category, 'page_obj': page_obj}
    return render(request, 'blog/list.html', context)


def my_post_list(request):
    posts = Post.objects.filter(owner_id=request.user.id)
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'blog/my_post.html', context)


def post_detail(request, post_id):
    # 文章详情页
    post = get_object_or_404(Post, id=post_id)

    # 用文章id来实现的上下篇
    prev_post = Post.objects.filter(id__lt=post_id).last()  # 上一篇
    next_post = Post.objects.filter(id__gt=post_id).first()  # 下一篇
    Post.objects.filter(id=post_id).update(pv=F('pv') + 1)  # 浏览
    comments = Comment.objects.filter(post_id=post_id)
    comment_form = CommentForm()
    is_favorite = len(Favorite.objects.filter(user_id=request.user.id, post_id=post_id))

    # 用发布日期来实现上下篇
    # date_prev_post = Post.objects.filter(add_date__lt=post.add_date).last()
    # date_next_post = Post.objects.filter(add_date__gt=post.add_date).first()
    context = {
        'post': post,
        'prev_post': prev_post,
        'next_post': next_post,
        'comments': comments,
        'comment_form': comment_form,
        'is_favorite': is_favorite
    }
    return render(request, 'blog/detail.html', context)


def search(request):
    """ 搜索视图 """
    keyword = request.GET.get('keyword')
    users = []
    # 没有搜索默认显示所有文章
    if not keyword:
        post_list = Post.objects.all()
    else:
        # 包含查询的方法，用Q对象来组合复杂查询
        post_list = Post.objects.filter(
            Q(title__icontains=keyword) | Q(desc__icontains=keyword) | Q(
                owner__userprofile__nickName__icontains=keyword))  # | Q(content__icontains=keyword))
        users = User.objects.filter(Q(username__icontains=keyword) | Q(userprofile__nickName__icontains=keyword))
    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj, 'users': users
    }
    return render(request, 'blog/search_list.html', context)


def archives(request, year, month):
    # 文章归档列表页
    post_list = Post.objects.filter(add_date__year=year, add_date__month=month)
    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj, 'year': year, 'month': month, 'count': post_list.count()}
    return render(request, 'blog/archives_list.html', context)


@login_required(login_url='users:login')
def post_comment(request, post_id, parent_comment_id=None):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        post = Post.objects.get(id=post_id)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            return redirect('blog:post_detail', post_id)
        else:
            return HttpResponse('内容有误，请重新填写')
    else:
        form = CommentForm()

    context = {
        'form': form,
        'post_id': post_id,
        'parent_comment_id': parent_comment_id
    }
    return render(request, 'blog/detail.html', context)


@login_required(login_url='users:login')
def post_release(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            post_id = new_post.id
            return redirect('blog:post_detail', post_id)
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'blog/release.html', context)


@login_required(login_url='users:login')
def post_edit(request, post_id):
    user_id = Post.objects.get(id=post_id).owner_id
    if user_id != request.user.id:
        messages.error(request, '没有编辑权限！')
        return redirect('blog:post_detail', post_id)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            Post.objects.filter(id=post_id).update(
                title=post.title,
                desc=post.desc,
                category_id=post.category.id,
                content=post.content
            )
            return redirect('blog:post_detail', post_id)
    else:
        form = PostForm()
    context = {'form': form, 'user_id': user_id}
    return render(request, 'blog/edit.html', context)


@login_required(login_url='users:login')
def post_delete(request, post_id):
    user = Post.objects.get(id=post_id).owner_id
    if request.user.id == user:
        Post.objects.filter(id=post_id).delete()
    return redirect('/')


@login_required(login_url='users:login')
def comment_delete(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    post_id = comment.post_id
    Comment.objects.filter(id=comment_id).delete()
    return redirect('blog:post_detail', post_id)


# def comment_sidebar(request):
#     comment = Comment.objects.all()
#     return render(request, 'blog/sidebar/comment.html')
@login_required(login_url='users:login')
def favorite_add(request, post_id):
    user = request.user.id
    post = post_id
    Favorite.objects.create(user_id=user, post_id=post)
    return redirect('blog:post_detail', post_id)


@login_required(login_url='users:login')
def favorite_del(request, post_id):
    user = request.user.id
    post = post_id
    Favorite.objects.filter(user_id=user, post_id=post).delete()
    return redirect('blog:post_detail', post_id)


# @login_required(login_url='users:login')
def my_favorite(request):
    post = Favorite.objects.filter(user_id=request.user.id).values('post_id')
    posts = []
    for it in post:
        posts += Post.objects.filter(id=it['post_id'])
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'blog/my_favorite.html', context)


def post_list(request, user_id):
    user = User.objects.get(id=user_id)
    posts = Post.objects.filter(owner_id=user_id)
    paginator = Paginator(posts, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj, 'user': user}
    return render(request, 'blog/post_list.html', context)

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static category %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}博客源{% endblock %}</title>
	<!-- <link rel="stylesheet" href="{% static 'users/bulma.css' %}"> -->
{#    <script type="text/javascript" src="{% static 'ckeditor5/ckeditor.js' %}"></script>#}
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <script src="{% static 'ckeditor5/ckeditor.js' %}"></script>
    <script src="{% static 'ckeditor5/translations/zh.js' %}"></script>
    <script src="{% static 'ckeditor5/config.js' %}"></script>
{#    <link rel="stylesheet" href="{% static '/layui/css/layui.css' %}" />#}
    <script src="https://cdn.ckeditor.com/ckeditor5/35.4.0/classic/ckeditor.js"></script>
    {% block head %}
    {% endblock %}
</head>

<body>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
        <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
                <div class="navbar-brand">
                    <a class="navbar-item" href="/">
                        <img src="{% static 'users/images/logo.png' %}" width="32" height="32">
                    </a>

                    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                        data-target="navbarBasicExample">
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                        <span aria-hidden="true"></span>
                    </a>
                </div>

                <div id="navbarBasicExample" class="navbar-menu">
                    <div class="navbar-start">

                        {% block navbar-start %}
                        <a class="navbar-item" href="/">
                            首页
                        </a>
                        <a class="navbar-item" href="{% url 'blog:post_release' %}">
                            发布
                        </a>
                        <a class="navbar-item" href="{% url 'blog:my_post' %}">
                            我的
                        </a>
                        <a class="navbar-item" href="{% url 'blog:my_favorite' %}">
                            收藏
                        </a>
    					{% get_category_list as category_list %}
    						{% for category in category_list %}
    						<a class="navbar-item" href="{% url 'blog:category_list' category.id %}">
    							{{ category.name }}
    						</a>
    						{% endfor %}
                        {% endblock %}
                    </div>
                    <div class="navbar-end">
                        <form action="{% url 'blog:search' %}" method="get" style="padding-top: 10px">
                            {% csrf_token %}
                            <div class="field has-addons">
                                <div class="control is-expanded">
                                    <input type="search" class="input" name="keyword" placeholder="Search" value="{{ keyword }}">
                                </div>
                                <div class="control">
                                  <input  class="button is-primary" type="submit" value="搜索">
                                </div>
                              </div>
                        </form>
                        {% block navbar-end %}
                        <div class="navbar-item">
                            {% if request.user.is_authenticated %}
                                <div class="buttons">
                                    <a class="button is-primary" href="{% url 'users:user_profile' request.user.username %}" target="_blank">
                                        <strong>
                                            {{ request.user.username }}
                                        </strong>
                                    </a>
                                    <a href="{% url 'users:logout' %}" class="button is-primary">退出</a>
                                </div>
                            {% else %}
                            <div class="buttons">
                                <a class="button is-primary" href="{% url 'users:register' %}" target="_blank">
                                    <strong>注册</strong>
                                </a>
                                <a class="button is-light" href="{% url 'users:login' %}" target="_blank">
                                    登录
                                </a>
                            </div>
                            {% endif %}
                        </div>
                        {% endblock %}
                    </div>
                </div>
        </nav>
    {% block body %}
        <section class="section">
            <div class=" container">
                <div class="columns">
                    <div class="column is-8">
                        {% block section %}
                            {% block archives %}
                            {% endblock  %}
                        {% if page_obj %}
                        {% for post in page_obj %}
                        <div class="box">
                            <h1 class="is-size-5 has-text-weight-bold">
                                <a href="{% url 'blog:post_detail' post.id %}"> {{ post.title }}</a>
                            </h1>
                            <div class=" is-size-7 has-text-grey-light pt-1 pb-1">
                                <span class="mr-3">作者：{{ post.owner }}</span> <span>发布日期：{{ post.add_date }}</span>
                            </div>
                            <!-- https://docs.djangoproject.com/zh-hans/3.2/ref/templates/builtins/#truncatechars  官方文档 -->
                            <p class="mt-3">{{ post.desc|truncatechars:500 }}</p>
                        </div>
                        {% endfor %}
                        {% else %}
                        <div class="box">
                            <p class="has-text-danger">文章不存在！</p>
                        </div>
                        {% endif %}
                        <!--  文档： https://docs.djangoproject.com/zh-hans/3.2/ref/paginator/#django.core.paginator.Paginator -->
                        {% if page_obj %}
                            <nav class="pagination is-centered" role="navigation" aria-label="pagination">
                            {% if page_obj.has_previous %}
                                <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            {% endif %}
                            {% if page_obj.has_next %}
                            <a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
                            {% endif %}
                            <ul class="pagination-list">
                            {% if page_obj.has_previous %}
                                <li><a class="pagination-link" aria-label="Goto page 45" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                            {% endif %}
                                <li><a class="pagination-link is-current" aria-label="Page {{ page_obj.number }}" aria-current="page" href='?page={{ page_obj.number }}'>{{ page_obj.number }}</a></li>
                            {% if page_obj.has_next %}
                                <li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}" aria-label="Goto page {{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                            {% endif %}
                            </ul>
                            </nav>
                            {% endif %}
                        {% endblock %}
                    </div>
                    <div class="column is-4">

                        {% block right %}
                        {% get_sidebar_list as sidebar_list %}

                        {% for sidebar in sidebar_list %}
                        <div class="box">
                            <h1 class=" is-size-5 title">{{ sidebar.title }}</h1>
                            <p>{{ sidebar.get_content|safe }}</p>
                        </div>

                        {% endfor %}

                        {% endblock %}

                    </div>
                </div>

            </div>
        </section>
    {% endblock %}
        {% block footer %}
        <footer class="footer container">
            <div class=" has-text-centered">
                Developed by Rezarc 2022 - 2023 ® All Rights Reserved
            </div>
        </footer>
        {% endblock %}

</body>

</html>

blog/templates/blog/comment.html
{% extends 'blog/base.html' %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block title %}
    {{ post.title }} - 博客源 - 基于Django的在线博客网站
{% endblock %}
{% block section %}
<div class="box">
    <h1 class="is-size-5 has-text-weight-bold">
        <a> {{ post.title }}</a>
    </h1>
    <div class=" is-size-7 has-text-grey-light pt-1 pb-1">
        <span class="mr-3">作者：<a href="{% url 'users:user_profile' post.owner %}"}>{{ post.owner }}</a></span> <span>发布日期：{{ post.add_date }}</span> <span>浏览量：{{ post.pv }}</span>
    </div>
    <div class="content">
        {{ post.content|safe }}
    </div>
    {% if request.user.is_authenticated %}
        {% if post.owner_id == request.user.id %}
            <span class="is-size-7">
                <a href="{% url 'blog:post_edit' post.id %}">修改</a>
                <a href="{% url 'blog:post_delete' post.id %}">删除</a>
            </span>
        {% endif %}
    {% endif %}
    {% if request.user.is_authenticated %}
        {% if is_favorite %}
            <span class="is-size-7">
                <a href="{% url 'blog:favorite_del' post.id %}">取消收藏</a>
            </span>
        {% else %}
            <span class="is-size-7">
                <a href="{% url 'blog:favorite_add' post.id %}">收藏</a>
            </span>
        {% endif %}
    {% endif %}

</div>

<div class="box">
    <div class="level">
        <div class="level-left">
            
            {% if prev_post %}
            <span>上一篇：</span><a href="{% url 'blog:post_detail' prev_post.id %}" class="level-item">{{ prev_post.title }}</a>
            {% else %}
            <span class=" has-text-danger-dark is-size-7">无上一篇</span>
            {% endif %}
        </div>
        <div class="level-right">
            {% if next_post %}
            <span>下一篇：</span><a href="{% url 'blog:post_detail' next_post.id %}" class="level-item">{{ next_post.title }}</a>
            {% else %}
            <span class=" has-text-danger-dark is-size-7">已经是最后一篇</span>
            {% endif %}
        </div>
    </div>
</div>

<div class="box">
    {% if request.user.is_authenticated %}
        <form action="{% url 'blog:post_comment' post.id %}" method="post">
                {% csrf_token %}
                {{ comment_form.media }}
                {{ comment_form.body }}
                <input type="submit" style="margin-top: 1em" class="button is-link" value="评论">
        </form>
    {% else %}
        <h5 class="row justify-content-center">
            请<a href="{% url 'users:login' %}">登录</a>后回复
        </h5>
    {% endif %}
</div>
<div class="box">
    <h4>共有{{ comments.count }}条评论</h4>
    <div>
        {% for comment in comments %}
            <hr>
            <p>
            <a href="{% url 'users:user_profile' comment.user %}">
                <strong style="color: pink">
                    {{ comment.user }}
                </strong>
            </a> 于
                <span style="color: green">
                    {{ comment.created }}
                </span> 评论：
                {% if comment.user_id == request.user.id %}
                    <span class="is-size-7">
                        <a href="{% url 'blog:comment_delete' comment.id %}">删除</a>
                    </span>
                {% else %}
                    {% if post.owner_id == request.user.id %}
                    <span class="is-size-7">
                        <a href="{% url 'blog:comment_delete' comment.id %}">删除</a>
                    </span>
                    {% endif %}
                {% endif %}
            </p>
            <div id="comment_elem_{{ comment.id }}">{{ comment.body|safe }}</div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

blog/templates/blog/list.html
{% extends 'blog/base.html' %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block title %}
{{ user.username }}发布的文章
{% endblock %}

blog/templates/blog/release.html
{% extends 'blog/base.html' %}

{% block title %}
发布文章
{% endblock %}

{% block body %}
    <h6 class="has-text-centered">发布文章</h6>
    {% if user.is_authenticated %}
        <div class="has-text-centered">
            <form class=action="{% url 'blog:post_release' %}" method="post">
                {% csrf_token %}
                    <div class="field is-horizontal">
                      <div class="field-label is-normal">
                        <label for="{{ form.title.id_for_label }}" class="label">{{ form.title.label }}</label>
                      </div>
                      <div class="field-body">
                        <div class="field">
                          <div class="control">
                             {{ form.title }}
                          </div>
                        </div>
                      </div>
                  </div>
                    <div class="field is-horizontal">
                      <div class="field-label is-normal">
                        <label for="{{ form.desc.id_for_label }}" class="label">{{ form.desc.label }}</label>
                      </div>
                      <div class="field-body">
                        <div class="field">
                          <div class="control">
                             {{ form.desc }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="field is-horizontal">
                      <div class="field-label is-normal">
                        <label for="{{ form.content.id_for_label }}" class="label">{{ form.content.label }}</label>
                      </div>
                      <div class="field-body">
                        <div class="field">
                          <div class="control">
                              {{ form.media }}
                                {{ form.content }}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="field is-horizontal">
                      <div class="field-label is-normal">
                        <label for="{{ form.category.id_for_label }}" class="label">{{ form.category.label }}</label>
                      </div>
                      <div class="field-body">
                        <div class="field">
                          <div class="control">
                             {{ form.category }}
                          </div>
                        </div>
                      </div>
                    </div>
                <input type="submit" style="margin-top: 1em" class="button is-link" value="发表">
            </form>
        </div>
    {% else %}
        <h5 class="row justify-content-center">
            请<a href="{% url 'users:login' %}">登录</a>后发表
        </h5>
    {% endif %}

{% endblock %}