blog/urls.py
from django.urls import path 
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category_list, name='category_list'),
    path('release/', views.post_release, name='post_release'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post_edit/<int:post_id>/', views.post_edit, name='post_edit'),
    path('delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('search/', views.search, name='search'),
    path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
    path('comment/<int:post_id>/', views.post_comment, name='post_comment'),
    path('comment_delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('my_post/', views.my_post_list, name='my_post'),
    path('favorite_add/<int:post_id>/', views.favorite_add, name='favorite_add'),
    path('favorite_del/<int:post_id>/', views.favorite_del, name='favorite_del'),
    path('my_favorite/', views.my_favorite, name='my_favorite'),
    path('post_list/<int:user_id>/', views.post_list, name='post_list'),
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'  # 定义一个命名空间  用于区分不同应用的连接地址

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.register, name='register'),
    path('active/<active_code>', views.active_user, name='active_user'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('forget_pwd_url/<active_code>', views.forget_pwd_url, name='forget_pwd_url'),
    # path('my_profile/', views.my_profile, name='my_profile'),
    path('user_profile/<username>/', views.user_profile, name='user_profile'),
    path('logout/', views.logout_view, name='logout'),
    path('editor_users/', views.editor_users, name='editor_users'),
    path('modify_pwd/', views.modify_pwd, name='modify_pwd'),
    path('check_pwd/', views.check_pwd, name='check_pwd'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    USER_GENDER_TYPE = (
        ('male', '男'),
        ('female', '女'),
    )
    owner = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='用户')  # 一对一扩展
    nickName = models.CharField('昵称', max_length=50, default='')
    desc = models.CharField('个人简介', max_length=200, blank=True, default='这个人很懒，什么都没有写。') # 个人简介
    birth = models.DateField('生日', null=True, blank=True)
    gender = models.CharField('性别', max_length=6, choices=USER_GENDER_TYPE, default='male')     # 选择框  默认 male
    image = models.ImageField(upload_to='images/%Y/%m', default='images/default.png', max_length=100, verbose_name='用户头像')   #存储目录, 默认头像, 最大长度, 默认值

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.owner.username


class EmailVerifyRecord(models.Model):
    SEND_TYPE_CHOICES = (
        ('register', '注册'),
        ('forget', '找回密码')
    )
    code = models.CharField('验证码', max_length=6)
    email = models.EmailField('邮箱', max_length=35)
    send_type = models.CharField(choices=SEND_TYPE_CHOICES, default='register', max_length=25)

    class Meta:
        verbose_name = '验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.code

users/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=35, widget=forms.TextInput(attrs={
        'class': 'input', 'placeholder': '用户名/邮箱'
    }))
    password = forms.CharField(label='密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '密码'
    }))

    # 验证密码
    def clean_password(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username == password:
            raise forms.ValidationError('用户名与密码不能相同')
        return password


# 注册表单
class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='用户名', max_length=35, widget=forms.TextInput(attrs={
        'class': 'input', 'placeholder': '用户名'
    }))
    email = forms.EmailField(label='邮箱', max_length=35, widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': '邮箱'
    }))
    password = forms.CharField(label='密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '密码'
    }))
    password1 = forms.CharField(label='再次输入密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '再次输入密码'
    }))

    class Meta:
        model = User
        # fields = ('username', 'password')
        fields = ('username', 'email', 'password')

    # 验证用户名是否存在
    def clean_username(self):
        username = self.cleaned_data.get('username')
        exists = User.objects.filter(username=username).exists()
        if exists:
            raise forms.ValidationError('用户名已存在')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        exists = User.objects.filter(email=email).exists()
        if exists:
            raise forms.ValidationError('邮箱已注册')
        return email

    # 验证密码是否相等
    def clean_password1(self):
        if self.cleaned_data['password'] != self.cleaned_data['password1']:
            raise forms.ValidationError('两次密码输入不一致')
        return self.cleaned_data['password1']


# 忘记密码
class ForgetPwdForm(forms.Form):
    email = forms.EmailField(label='邮箱', max_length=35, widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': '邮箱'
    }))


class CheckPwdForm(forms.Form):
    password = forms.CharField(label='输入新密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '密码'
    }))


# 修改密码
class ModifyPwdForm(forms.Form):
    password = forms.CharField(label='输入新密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '密码'
    }))
    password1 = forms.CharField(label='再次输入密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '再次输入密码'
    }))


class UserForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'input'
    }))
    birth = forms.DateField(widget=forms.DateInput(attrs={
        'class': 'input'
    }))

    class Meta:
        model = User
        fields = ('email',)


# 编辑个人信息表单
class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('nickName', 'desc', 'birth', 'gender', 'image')

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend  # 身份验证后端
from django.db.models import Q
from django.contrib.auth.hashers import make_password
from .forms import LoginForm, RegisterForm, ForgetPwdForm, ModifyPwdForm, UserForm, UserProfileForm, CheckPwdForm
from .models import EmailVerifyRecord, UserProfile, User
from django.core.mail import send_mail
import random
import string
from django.contrib.auth.decorators import login_required


class MyBackend(ModelBackend):
    # 邮箱登录注册
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = User.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):  # 加密明文密码
                return user
        except Exception as e:
            return None


def active_user(request, active_code):
    # 比对验证码
    all_records = EmailVerifyRecord.objects.filter(code=active_code)
    if all_records:
        for it in all_records:
            email = it.email
            user = User.objects.get(email=email)
            user.is_staff = True
            user.save()
    else:
        messages.error(request, '链接有误')
        return redirect('/')
    return redirect('users:login')


def loginView(request):
    if request.method != 'POST':  # 是否 POST 格式
        form = LoginForm()  # 空表单
    else:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']  # 获取帐号
            password = form.cleaned_data['password']  # 获取密码
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if not request.user.is_staff:
                    messages.error(request, '帐号未激活，清前往注册邮箱查看邮件激活')
                    logout(request)
                    return redirect('users:login')
                return redirect('/')
            else:
                messages.error(request, '帐号或密码错误')
                return redirect('users:login')
    context = {'form': form}
    return render(request, 'users/login.html', context)


def check_pwd(request):
    if request.method != 'POST':
        form = CheckPwdForm()
    else:
        form = CheckPwdForm(request.POST)
        if form.is_valid():
            username = request.user.username
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                return redirect('users:modify_pwd')
            else:
                messages.error(request, '密码错误')
                return redirect('users:user_profile', username)
    context = {'form': form}
    return render(request, 'users/check_pwd.html', context)


def random_str(length=6):
    # 生成随机字符串
    chars = string.ascii_letters + string.digits
    code = ''.join(random.sample(chars, length))
    return code


def send_register_email(email, send_type='register'):
    email_record = EmailVerifyRecord()
    code = random_str()
    email_record.code = code
    email_record.email = email
    email_record.send_type = send_type
    # email_record.add_time = datetime.now()
    email_record.save()

    if send_type == 'register':
        email_title = '博客的注册激活链接'
        email_body = '请点击以下链接激活账号：http://127.0.0.1:8000/users/active/{0}'.format(code)

        send_status = send_mail(email_title, email_body, 'rezarc@qq.com', [email])
        if send_status:
            pass

    elif send_type == 'forget':
        email_title = '找回密码链接'
        email_body = '请点击以下链接修改密码：http://127.0.0.1:8000/users/forget_pwd_url/{0}'.format(code)

        send_status = send_mail(email_title, email_body, 'rezarc@qq.com', [email])
        if send_status:
            pass


# 注册页面
def register(request):
    if request.method != 'POST':
        form = RegisterForm()
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data.get('password'))
            # new_user.username = form.cleaned_data.get('email')
            new_user.save()
            send_register_email(form.cleaned_data.get('email'), 'register')
            messages.error(request, '注册成功')
            return redirect('/')
    context = {'form': form}
    return render(request, 'users/register.html', context)


def forget_pwd(request):
    if request.method == 'GET':
        form = ForgetPwdForm()
    elif request.method == 'POST':
        form = ForgetPwdForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            exists = User.objects.filter(email=email).exists()
            if exists:
                send_register_email(email, 'forget')
                messages.error(request, '邮件已经发送，请查收')
                return redirect('users:login')
            else:
                messages.error(request, '邮箱未注册')
                return redirect('users:forget_pwd')
    context = {'form': form}
    return render(request, 'users/forget_pwd.html', context)


def forget_pwd_url(request, active_code):
    record = EmailVerifyRecord.objects.get(code=active_code)
    if record:
        if request.method != 'POST':
            form = ModifyPwdForm()
        else:
            form = ModifyPwdForm(request.POST)
            if form.is_valid():
                email = record.email
                user = User.objects.get(email=email)
                user.password = make_password(form.cleaned_data.get('password'))
                user.save()
                messages.error(request, '修改成功')
                EmailVerifyRecord.objects.get(code=active_code).delete()
                return redirect('users:login')
            else:
                messages.error(request, '链接有误')
                return redirect('/')
    else:
        messages.error(request, '修改失败')
        return redirect('users:forget_pwd_url')
    context = {'form': form}
    return render(request, 'users/modifypwd.html', context)


def modify_pwd(request):
    if request.method != 'POST':
        form = ModifyPwdForm()
    else:
        form = ModifyPwdForm(request.POST)
        if form.is_valid():
            if form.cleaned_data.get('password') == form.cleaned_data.get('password1'):
                user = User.objects.get(id=request.user.id)
                user.password = make_password(form.cleaned_data.get('password'))
                user.save()
                messages.error(request, '修改成功')
            else:
                messages.error(request, '两次密码不相同')
            return redirect('/')
        else:
            messages.error(request, '修改失败')
            return redirect('users:forget_pwd_url')
    context = {'form': form}
    return render(request, 'users/modifypwd.html', context)


def user_profile(request, username):
    user = User.objects.get(username=username)
    is_profile = len(UserProfile.objects.filter(owner_id=user.id))
    if is_profile:
        user_profile = UserProfile.objects.get(owner_id=user.id)
    else:
        user_profile = []
    context = {'user': user, 'user_profile': user_profile}
    return render(request, 'users/user_profile.html', context)


def logout_view(request):
    logout(request)
    return redirect('/')


@login_required(login_url='users:login')
def editor_users(request):
    """ 编辑用户信息 """
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        try:
            userprofile = user.userprofile
            form = UserForm(request.POST, instance=user)
            user_profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
            if form.is_valid() and user_profile_form.is_valid():
                form.save()
                user_profile_form.save()
                return redirect('users:user_profile', user.username)
            else:
                messages.error(request, '信息格式有误！')
        except UserProfile.DoesNotExist:
            form = UserForm(request.POST, instance=user)
            user_profile_form = UserProfileForm(request.POST, request.FILES)
            if form.is_valid() and user_profile_form.is_valid():
                form.save()
                new_user_profile = user_profile_form.save(commit=False)
                new_user_profile.owner = request.user
                new_user_profile.save()

                return redirect('users:user_profile', user.username)
    else:
        try:
            userprofile = user.userprofile
            form = UserForm(instance=user)
            user_profile_form = UserProfileForm(instance=userprofile)
        except UserProfile.DoesNotExist:
            form = UserForm(instance=user)
            user_profile_form = UserProfileForm()
    return render(request, 'users/editor_users.html', locals())

users/templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}<title>用户登录</title>{% endblock head %}

    <link rel="stylesheet" href="{% static 'users/bulma.css' %}">

</head>
<body>
    <div class="container">

        {% block content %}

        {% endblock content%}

    </div>
</body>
</html>

users/templates/users/editor_users.html
{% extends 'blog/base.html' %}

{% block title %}
    编辑信息
{% endblock  %}

{% block body %}
    <section class="section">
        <div class="container">

            <div class="columns">
                <div class="column is-2">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">个人中心</p>
                            <a href="" class="card-header-icon" aria-label="more options">
                                <span class="icon">
                                    <i class="fas fa-angle-down" aria-hidden="true"></i>
                                </span>
                            </a>
                        </header>
                        <div class="card-content menu">
                            <ul class="content menu-list">
                                <li><a href="{% url 'users:user_profile' user.username %}">个人信息</a></li>
                                <li><a href="{% url 'users:check_pwd' %}">修改密码</a></li>

                            </ul>
                        </div>

                    </div>
                    <div class="card">
                            <header class="card-header">
                                <p class="card-header-title">内容管理</p>
                                <a href="#" class="card-header-icon" aria-label="more options">
                                    <span class="icon">
                                        <i class="fas fa-angle-down" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </header>
                            <div class="card-content menu">
                                <ul class="content menu-list">
                                    <li><a href="{% url 'blog:post_release' %}">添加文章</a></li>
                                    <li><a href="{% url 'blog:my_post' %}">已发布</a></li>
                                </ul>
                            </div>

                    </div>
                </div>
                <div class="column is-10">
                    <div class="box is-radiusless is-shadowless">

                        <div class="tabs">
                            <ul>
                              <li class="is-active"><a>编辑信息</a></li>
                            </ul>
                        </div>


                    <form action="{% url 'users:editor_users' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                              <label for="{{ form.email.id_for_label }}" class="label">{{ form.email.label }}</label>
                            </div>
                            <div class="field-body">
                              <div class="field">
                                <div class="control">
                                    {{ form.email }}
                                </div>
                              </div>
                            </div>
                        </div>
                          {% for field in user_profile_form %}
                          <div class="field is-horizontal">
                              <div class="field-label is-normal">
{#                                <label for="{{ user_profile_form.nickName.id_for_label }}" class="label">{{ user_profile_form.nickName.label }}</label>#}
                                <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                              </div>
                              <div class="field-body">
                                <div class="field">
                                  <div class="control">
                                     {{ field }}
{#                                      <input type="text" class="form-control" name="nickName">#}
                                  </div>
                                </div>
                              </div>
                          </div>
                          {% endfor %}
                          <input class=" button is-primary is-pulled-right" type="submit" value="保存修改">
                          <div class=" is-clearfix"></div>
                      </form>
                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

users/templates/users/user_profile.html
{% extends 'blog/base.html' %}

{% block title %}
    {% if user_profile %}
        {{ user_profile.nickName }}的个人空间
    {% else %}
        {{ user.username }}的个人空间
    {% endif %}
{% endblock %}

{% block body %}
    <section class="section">
        <div class="container">

            <div class="columns">
                <div class="column is-3">
                    <div class="card">
                        <header class="card-header">
                            <p class="card-header-title">
                            {% if is_profile %}
                                {{ user_profile.nickName }}的个人空间
                            {% else %}
                                {{ user.username }}的个人空间
                            {% endif %}
                            </p>
                            <a href="" class="card-header-icon" aria-label="more options">
                                <span class="icon">
                                    <i class="fas fa-angle-down" aria-hidden="true"></i>
                                </span>
                            </a>
                        </header>
                        <div class="card-content menu">
                            <ul class="content menu-list">
                                <li><a href="{% url 'users:user_profile' user.username %}">个人信息</a></li>
                                {% if request.user.is_authenticated %}
                                    {% if user.id == request.user.id %}
                                        <li><a href="{% url 'users:check_pwd' %}">修改密码</a></li>
                                    {% else %}
                                        {% if user.userprofile %}
                                            {% if user.userprofile.get_gender_display == '男' %}
                                                <li><a href="{% url 'blog:post_list' user.id %}">他发布的</a></li>
                                            {% else %}
                                                <li><a href="{% url 'blog:post_list' user.id %}">她发布的</a></li>
                                            {% endif %}
                                        {% else %}
                                            <li><a href="{% url 'blog:post_list' user.id %}">ta发布的</a></li>
                                        {% endif %}
                                    {% endif %}
                                {% else %}
                                    {% if user.userprofile %}
                                        {% if user.userprofile.get_gender_display == '男' %}
                                            <li><a href="{% url 'blog:post_list' user.id %}">他发布的</a></li>
                                        {% else %}
                                            <li><a href="{% url 'blog:post_list' user.id %}">她发布的</a></li>
                                        {% endif %}
                                    {% else %}
                                        <li><a href="{% url 'blog:post_list' user.id %}">ta发布的</a></li>
                                    {% endif %}
                                {% endif %}
                            </ul>
                        </div>

                    </div>
                    <div class="card">
                    {% if user.is_authenticated %}
                        {% if user.id == request.user.id %}
                            <header class="card-header">
                                <p class="card-header-title">内容管理</p>
                                <a href="#" class="card-header-icon" aria-label="more options">
                                    <span class="icon">
                                        <i class="fas fa-angle-down" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </header>
                            <div class="card-content menu">
                                <ul class="content menu-list">
                                    <li><a href="{% url 'blog:post_release' %}">添加文章</a></li>
                                    <li><a href="{% url 'blog:post_list' user.id %}">我发布的</a></li>
                                </ul>
                            </div>
                        {% endif %}
                    {% endif %}
                    </div>
                </div>
                <div class="column is-10">
                    <div class="box is-radiusless is-shadowless">

                        <div class="tabs">
                            <ul>
                              <li class="is-active"><a>账号信息</a></li>    {# 替换的地方 #}
                            </ul>
                        </div>

                    {% block content %}
                    <div class="columns is-mobile" style="border-bottom: #ededed solid 1px; padding-bottom: 1rem">
                        <div class="column is-narrow">
                            <figure class="image is-96x96">

                                {% if user.userprofile.image %}     {# 调用是否存在 #}
                                    <img class="is-rounded" src="{{ MEDIA_URL }}{{ user.userprofile.image }}">
                                    {% else %}
                                    <img class="is-rounded" src="{{ MEDIA_URL }}images/default.png">
                                {% endif %}


                            </figure>
                        </div>
                        <div class="column is-narrow">
                            <div style="padding-top: 1.5rem;">

                                {% if user.userprofile.nickName %}
                                    <h1 class="title is-size-4">{{ user.userprofile.nickName }}</h1>
                                    {% else %}
                                    <h1 class="title is-size-4">{{ user.username }}</h1>
                                {% endif %}


                                {% if user.userprofile.desc %}
                                    <p class="subtitle is-size-6">{{ user.userprofile.desc }}</p>
                                    {% else %}
                                    <p class="subtitle is-size-6">暂未设置个性签名</p>
                                {% endif %}


                            </div>
                        </div>
                        {% if user.is_authenticated %}
                            {% if user.id == request.user.id %}
                                <div class="column is-narrow-mobile">
                                    <a class=" button is-light is-pulled-right" href="{% url 'users:editor_users' %}" style="margin-top: 1.8rem">修改信息</a>
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>

                    <div class="columns" style="padding:1rem 0; ">
                        <div class="column is-2">
                            <p>个人信息</p>
                        </div>
                        <div class="column">
                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">用户名</span>
                                </div>
                                <div class="column is-narrow">
                                    <span class=" has-text-black-ter">{{ user.username }}</span>
                                </div>
                            </div>
                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">昵称</span>
                                </div>
                                    <div class="column is-narrow">
                                        {% if user.userprofile.nickName %}
                                        <span class=" has-text-black-ter">{{ user.userprofile.nickName }}</span>
                                        {% else %}
                                        <span class=" has-text-black-ter">暂未设置用户昵称</span>
                                        {% endif %}

                                    </div>
                                <!-- <div class="column has-text-right">
                                    <a href="">更改类型</a>
                                </div> -->

                            </div>

                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">性别</span>
                                </div>
                                <div class="column is-narrow">
                                    {% if user.userprofile %}
                                        <span class=" has-text-black-ter">{{ user.userprofile.get_gender_display }}</span>
                                    {% else %}
                                        <span class=" has-text-black-ter">暂未设置</span>
                                    {% endif %}
                                </div>

                            </div>
                            <div class="columns is-mobile" style="border-bottom: #ededed solid 1px">
                                <div class="column is-2">
                                   <span class=" has-text-grey-light">邮箱</span>
                                </div>
                                <div class="column is-narrow">
                                    <span class=" has-text-black-ter">{{ user.email }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endblock  %}
                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}